server:
  port: 3344
spring:
  application:
    name: cloud-config-3344
  cloud:
    config:
      server:
        git:
          uri: git@github.com:liuxuejava/microservice-config.git
          default-label: master
          search-paths:
           - microservice-config
eureka:
  client:
    service-url:
     defaultZone: http://eureka7001.com:7001/eureka/